# -*- coding: utf-8 -*-
"""AidMatch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AAaYEc-0XSigi-PJZ3o5ZYzS-rXw3Un
"""

import sys
import subprocess

# 1. Clear cached modules from memory if re-running
if "backend" in sys.modules:
    del sys.modules["backend"]

# 2. Install required dependencies
!pip install -q streamlit groq pyngrok
print("✅ Dependencies installed and memory cache cleared!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile backend.py
# import os
# import json
# import sqlite3
# import hashlib
# from typing import Dict, List, Any
# from groq import Groq
# 
# DB_FILE = "aidmatch.db"
# 
# def get_db_connection():
#     conn = sqlite3.connect(DB_FILE)
#     conn.row_factory = sqlite3.Row
#     return conn
# 
# def hash_password(password: str) -> str:
#     return hashlib.sha256(password.encode('utf-8')).hexdigest()
# 
# def init_db():
#     conn = get_db_connection()
#     cursor = conn.cursor()
# 
#     # 1. Users Table with Hashed Passwords
#     cursor.execute("""
#     CREATE TABLE IF NOT EXISTS users (
#         user_id INTEGER PRIMARY KEY AUTOINCREMENT,
#         email TEXT UNIQUE NOT NULL,
#         password_hash TEXT NOT NULL,
#         cnic TEXT UNIQUE NOT NULL,
#         full_name TEXT NOT NULL,
#         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
#     )
#     """)
# 
#     # 2. Programs Catalog Table
#     cursor.execute("""
#     CREATE TABLE IF NOT EXISTS programs (
#         program_id TEXT PRIMARY KEY,
#         name TEXT NOT NULL,
#         category TEXT NOT NULL,
#         provider TEXT NOT NULL,
#         eligibility_json TEXT NOT NULL,
#         official_url TEXT NOT NULL,
#         document_checklist TEXT NOT NULL,
#         apply_pathway TEXT NOT NULL
#     )
#     """)
# 
#     # 3. Privacy-Isolated Search History (Linked directly to user_id)
#     cursor.execute("""
#     CREATE TABLE IF NOT EXISTS search_history (
#         search_id INTEGER PRIMARY KEY AUTOINCREMENT,
#         user_id INTEGER NOT NULL,
#         category_searched TEXT NOT NULL,
#         input_profile_json TEXT NOT NULL,
#         eligible_program_ids TEXT NOT NULL,
#         timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#         FOREIGN KEY (user_id) REFERENCES users (user_id)
#     )
#     """)
# 
#     conn.commit()
#     conn.close()
# 
# # ---------------------------------------------------------
# # AUTHENTICATION & ISOLATED HISTORY
# # ---------------------------------------------------------
# def register_user(email: str, password: str, cnic: str, full_name: str) -> Dict[str, Any]:
#     conn = get_db_connection()
#     cursor = conn.cursor()
#     hashed = hash_password(password)
#     try:
#         cursor.execute("""
#             INSERT INTO users (email, password_hash, cnic, full_name)
#             VALUES (?, ?, ?, ?)
#         """, (email.lower().strip(), hashed, cnic.strip(), full_name.strip()))
#         conn.commit()
#         user_id = cursor.lastrowid
#         conn.close()
#         return {"success": True, "user": {"user_id": user_id, "email": email, "cnic": cnic, "name": full_name}}
#     except sqlite3.IntegrityError:
#         conn.close()
#         return {"success": False, "error": "An account with this Email or CNIC already exists."}
# 
# def authenticate_user(email: str, password: str) -> Dict[str, Any]:
#     conn = get_db_connection()
#     cursor = conn.cursor()
#     hashed = hash_password(password)
#     cursor.execute("""
#         SELECT user_id, email, cnic, full_name
#         FROM users
#         WHERE LOWER(email) = ? AND password_hash = ?
#     """, (email.lower().strip(), hashed))
#     row = cursor.fetchone()
#     conn.close()
# 
#     if row:
#         return {"success": True, "user": {"user_id": row["user_id"], "email": row["email"], "cnic": row["cnic"], "name": row["full_name"]}}
#     return {"success": False, "error": "Invalid Email or Password."}
# 
# def save_search_history(user_id: int, category: str, profile: dict, matches: list):
#     conn = get_db_connection()
#     cursor = conn.cursor()
#     cursor.execute("""
#         INSERT INTO search_history (user_id, category_searched, input_profile_json, eligible_program_ids)
#         VALUES (?, ?, ?, ?)
#     """, (user_id, category, json.dumps(profile), json.dumps(matches)))
#     conn.commit()
#     conn.close()
# 
# def get_user_search_history(user_id: int) -> List[Dict[str, Any]]:
#     conn = get_db_connection()
#     cursor = conn.cursor()
#     cursor.execute("""
#         SELECT search_id, category_searched, input_profile_json, eligible_program_ids, timestamp
#         FROM search_history
#         WHERE user_id = ?
#         ORDER BY timestamp DESC
#     """, (user_id,))
#     rows = cursor.fetchall()
#     conn.close()
# 
#     history = []
#     for row in rows:
#         history.append({
#             "search_id": row["search_id"],
#             "category": row["category_searched"],
#             "profile": json.loads(row["input_profile_json"]),
#             "matches": json.loads(row["eligible_program_ids"]),
#             "timestamp": row["timestamp"]
#         })
#     return history
# 
# def fetch_all_programs() -> List[Dict[str, Any]]:
#     conn = get_db_connection()
#     cursor = conn.cursor()
#     cursor.execute("SELECT * FROM programs")
#     rows = cursor.fetchall()
#     conn.close()
# 
#     programs = []
#     for row in rows:
#         programs.append({
#             "program_id": row["program_id"],
#             "name": row["name"],
#             "category": row["category"],
#             "provider": row["provider"],
#             "eligibility": json.loads(row["eligibility_json"]),
#             "official_url": row["official_url"],
#             "document_checklist": json.loads(row["document_checklist"]),
#             "apply_pathway": json.loads(row["apply_pathway"])
#         })
#     return programs
# 
# # ---------------------------------------------------------
# # DETERMINISTIC MATCHING ENGINE WITH DISABILITY SUPPORT
# # ---------------------------------------------------------
# def evaluate_eligibility(user_profile: Dict[str, Any], program: Dict[str, Any]) -> Dict[str, Any]:
#     rules = program["eligibility"]
#     reasons = []
#     missing_info = []
# 
#     is_disabled = user_profile.get("is_disabled", False)
# 
#     if program["category"] != user_profile.get("category"):
#         return {"status": "Ineligible", "reasons": ["Program belongs to a different domain"], "missing_info": []}
# 
#     # Income Evaluation
#     max_income = rules.get("max_income")
#     user_income = user_profile.get("monthly_income")
#     if max_income is not None and user_income is not None:
#         if user_income > max_income:
#             reasons.append(f"Monthly household income (PKR {user_income:,}) exceeds maximum limit of PKR {max_income:,}.")
# 
#     # Age Evaluation
#     min_age = rules.get("min_age", 0)
#     max_age = rules.get("max_age", 120)
#     user_age = user_profile.get("age")
#     if user_age is not None:
#         if user_age < min_age or user_age > max_age:
#             reasons.append(f"Age {user_age} is outside the allowed bracket of {min_age} to {max_age} years.")
# 
#     # Domicile / Region
#     allowed_regions = rules.get("allowed_regions", [])
#     user_region = user_profile.get("domicile")
#     if allowed_regions and user_region:
#         if "All" not in allowed_regions and user_region not in allowed_regions:
#             reasons.append(f"Domicile/Location '{user_region}' is not eligible. Allowed regions: {', '.join(allowed_regions)}.")
# 
#     # Driving License Check
#     requires_license = rules.get("requires_license", False)
#     has_license = user_profile.get("has_driving_license", False)
#     if requires_license and not has_license:
#         missing_info.append("Valid Learner or Permanent Driving License required.")
# 
#     # Education Qualification
#     min_edu = rules.get("min_education_level")
#     user_edu = user_profile.get("education_level")
#     edu_levels = ["Primary", "Matric", "Intermediate", "Bachelors", "Masters", "PhD"]
#     if min_edu and user_edu:
#         if user_edu in edu_levels and min_edu in edu_levels:
#             if edu_levels.index(user_edu) < edu_levels.index(min_edu):
#                 reasons.append(f"Educational level '{user_edu}' is below required baseline of '{min_edu}'.")
# 
#     # Disability Quota Rules
#     requires_disability = rules.get("disability_quota_only", False)
#     if requires_disability and not is_disabled:
#         reasons.append("Reserved exclusively for Persons with Disabilities (PWD) holding a NADRA Special CNIC / Certificate.")
# 
#     # Exemption for PWD candidates on laptop merit caps
#     if is_disabled and program["program_id"] == "CM_PUNJAB_LAPTOP":
#         reasons = [r for r in reasons if "Educational level" not in r]
# 
#     if reasons:
#         return {"status": "Ineligible", "reasons": reasons, "missing_info": missing_info}
#     elif missing_info:
#         return {"status": "Conditional", "reasons": ["Meets income & age bounds, but missing mandatory documents or licenses."], "missing_info": missing_info}
#     else:
#         status_msg = ["All criteria satisfied."]
#         if is_disabled:
#             status_msg.append("Eligible under Special Persons / Disability Reserved Quotas.")
#         return {"status": "Eligible", "reasons": status_msg, "missing_info": []}
# 
# def run_matching_pipeline(user_profile: Dict[str, Any]) -> List[Dict[str, Any]]:
#     all_programs = fetch_all_programs()
#     results = []
#     eligible_ids = []
# 
#     for prog in all_programs:
#         if prog["category"] == user_profile.get("category"):
#             eval_res = evaluate_eligibility(user_profile, prog)
#             matched_record = {
#                 "program": prog,
#                 "status": eval_res["status"],
#                 "reasons": eval_res["reasons"],
#                 "missing_info": eval_res["missing_info"]
#             }
#             results.append(matched_record)
#             if eval_res["status"] in ["Eligible", "Conditional"]:
#                 eligible_ids.append(prog["program_id"])
# 
#     save_search_history(
#         user_id=user_profile.get("user_id"),
#         category=user_profile.get("category", "General"),
#         profile=user_profile,
#         matches=eligible_ids
#     )
#     return results
# 
# # ---------------------------------------------------------
# # GROQ BILINGUAL AI CHATBOT
# # ---------------------------------------------------------
# class GroqAssistant:
#     def __init__(self, model_name: str = "openai/gpt-oss-20b"):
#         self.client = Groq(api_key=os.environ.get("GROQ_API_KEY", ""))
#         self.model_name = model_name
# 
#     def generate_bilingual_response(self, user_query: str, history: List[Dict[str, str]] = None) -> str:
#         system_prompt = (
#             "You are AidMatch AI (مددگار AI), an official assistant for Pakistani government welfare, "
#             "scholarships, disability quotas, free IT training, and bike/laptop schemes.\n"
#             "OPERATIONAL GUIDELINES:\n"
#             "1. Respond seamlessly in English or Urdu (اردو) depending on user input.\n"
#             "2. Highlight special disability quotas (2% reserved in HEC/Govt admissions & jobs) when asked.\n"
#             "3. Official Links Reference:\n"
#             "   - Scholarships & Welfare: https://bisp.gov.pk/, https://honhaarscholarship.punjabhec.gov.pk/, https://ehsaas.punjab.gov.pk/, https://pspa.punjab.gov.pk/what-we-do, https://scholarship.hec.gov.pk/, https://eservices.hec.gov.pk/, https://www.pass.gov.pk/, https://www.sef.org.pk/, https://pmyp.gov.pk/\n"
#             "   - Free Courses: https://navttc.gov.pk/courses/, https://digiskills.pk/, https://dlsei.hec.gov.pk/, https://www.psdf.org.pk/, https://www.kpitb.gov.pk/, https://www.tevta.gop.pk/, http://www.stevta.gos.pk/, https://buildyourfuture.withgoogle.com/, https://www.netacad.com/catalogs/learn, https://www.pakangels.com/hec-generative-ai-training-program/\n"
#             "   - Asset Schemes: https://bikes.punjab.gov.pk/, https://cmlaptophed.punjab.gov.pk/, https://pmyp.gov.pk/\n"
#             "4. Provide clean, bulleted step-by-step guidance."
#         )
# 
#         messages = [{"role": "system", "content": system_prompt}]
#         if history:
#             for msg in history:
#                 messages.append({"role": msg["role"], "content": msg["content"]})
#         messages.append({"role": "user", "content": user_query})
# 
#         try:
#             response = self.client.chat.completions.create(
#                 model=self.model_name,
#                 messages=messages,
#                 temperature=0.3,
#                 max_tokens=1024
#             )
#             return response.choices[0].message.content
#         except Exception as e:
#             return f"Error connecting to AI service: {str(e)}"

import os
import json
import sqlite3
import backend

# Reload backend to guarantee updated methods
import importlib
importlib.reload(backend)

if os.path.exists("aidmatch.db"):
    os.remove("aidmatch.db")

backend.init_db()

SEED_PROGRAMS = [
    # ------------------ SCHOLARSHIPS & WELFARE ------------------
    {
        "program_id": "HONHAAR_PUNJAB",
        "name": "CM Punjab Honhaar Undergraduate Scholarship",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Punjab Higher Education Commission (PHEC)",
        "eligibility_json": json.dumps({"max_income": 350000, "min_age": 16, "max_age": 30, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://honhaarscholarship.punjabhec.gov.pk/",
        "document_checklist": json.dumps(["Punjab Domicile", "Intermediate Marks Sheet (65%+ Arts / 70%+ Science)", "Family Income Affidavit (< PKR 350,000)", "CNIC / B-Form"]),
        "apply_pathway": json.dumps(["Register on honhaarscholarship.punjabhec.gov.pk", "Fill academic & household details", "Upload e-stamp income affidavit and submit"])
    },
    {
        "program_id": "BISP_OFFICIAL",
        "name": "Benazir Income Support Programme (BISP Official)",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "BISP Government of Pakistan",
        "eligibility_json": json.dumps({"max_income": 40000, "min_age": 18, "max_age": 80, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://bisp.gov.pk/",
        "document_checklist": json.dumps(["NADRA Biometric CNIC", "NSER Dynamic Survey Record"]),
        "apply_pathway": json.dumps(["Visit nearest BISP Dynamic Registration Center", "Complete NSER survey", "Receive payment notifications via 8171"])
    },
    {
        "program_id": "EHSAAS_PUNJAB",
        "name": "Ehsaas Rashan & Social Safety Punjab",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Ehsaas Program Punjab",
        "eligibility_json": json.dumps({"max_income": 50000, "min_age": 18, "max_age": 75, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://ehsaas.punjab.gov.pk/",
        "document_checklist": json.dumps(["CNIC Registered SIM", "Punjab Domicile / Address"]),
        "apply_pathway": json.dumps(["Register CNIC on ehsaas.punjab.gov.pk portal", "Get subsidy confirmation SMS for merchant stores"])
    },
    {
        "program_id": "PSPA_PROGRAMS",
        "name": "PSPA Welfare Schemes (Humqadam, Ba-Himmat & Masawaat)",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Punjab Social Protection Authority (PSPA)",
        "eligibility_json": json.dumps({"max_income": 45000, "min_age": 18, "max_age": 80, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://pspa.punjab.gov.pk/what-we-do",
        "document_checklist": json.dumps(["NADRA Special CNIC with Disability Logo (for Humqadam)", "Senior Citizen CNIC 65+ (for Ba-Himmat)", "Transgender CNIC (for Masawaat)"]),
        "apply_pathway": json.dumps(["Review program details on pspa.punjab.gov.pk/what-we-do", "Register at nearest PSPA/DHQ center with NADRA disability card"])
    },
    {
        "program_id": "HEC_NEED_BASED",
        "name": "HEC Need-Based Undergraduate Scholarship",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Higher Education Commission (HEC)",
        "eligibility_json": json.dumps({"max_income": 60000, "min_age": 17, "max_age": 30, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://scholarship.hec.gov.pk/",
        "document_checklist": json.dumps(["CNIC of Self & Father", "Monthly Utility Bills", "Father/Guardian Income Certificate", "Disability Certificate (if claiming PWD quota)"]),
        "apply_pathway": json.dumps(["Create profile on scholarship.hec.gov.pk", "Submit online form and select institution", "Provide financial records to university FAO office"])
    },
    {
        "program_id": "HEC_ESERVICES_PORTAL",
        "name": "HEC National & Overseas Merit Scholarships",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "HEC E-Services Portal",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 18, "max_age": 35, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Bachelors", "disability_quota_only": False}),
        "official_url": "https://eservices.hec.gov.pk/",
        "document_checklist": json.dumps(["Attested Degrees & Transcripts", "HAT/GRE Test Scorecard", "NADRA Special CNIC (for reserved seats)"]),
        "apply_pathway": json.dumps(["Register at eservices.hec.gov.pk", "Select active national/international calls", "Upload academic & disability documents"])
    },
    {
        "program_id": "SEF_SCHOLARSHIPS",
        "name": "Sindh Education Foundation (SEF) Student Grants",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Sindh Education Foundation",
        "eligibility_json": json.dumps({"max_income": 45000, "min_age": 10, "max_age": 22, "allowed_regions": ["Sindh"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://www.sef.org.pk/",
        "document_checklist": json.dumps(["B-Form / CNIC", "Sindh Domicile", "School Enrollment Certificate"]),
        "apply_pathway": json.dumps(["Apply directly via SEF partner schools", "Submit domicile & family financial records"])
    },
    {
        "program_id": "PMYP_SCHOLARSHIP",
        "name": "Prime Minister's Youth Financial Support Scheme",
        "category": "💰 Scholarships & Financial Assistance",
        "provider": "Prime Minister Youth Programme (PMYP)",
        "eligibility_json": json.dumps({"max_income": 80000, "min_age": 15, "max_age": 29, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://pmyp.gov.pk/",
        "document_checklist": json.dumps(["CNIC / B-Form", "Student Card", "Income proof of parents"]),
        "apply_pathway": json.dumps(["Apply online via pmyp.gov.pk", "Track application status through PM portal"])
    },

    # ------------------ COURSES ------------------
    {
        "program_id": "NAVTTC_COURSES",
        "name": "NAVTTC Prime Minister's High-Tech Skill Training",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "National Vocational and Technical Training Commission",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 18, "max_age": 40, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Matric", "disability_quota_only": False}),
        "official_url": "https://navttc.gov.pk/courses/",
        "document_checklist": json.dumps(["CNIC Copy", "Educational Certificates", "2 Passport Photos"]),
        "apply_pathway": json.dumps(["Browse courses at navttc.gov.pk/courses/", "Apply online or visit nearest institute", "Appear for interview/selection"])
    },
    {
        "program_id": "DIGISKILLS_FREE",
        "name": "DigiSkills 2.0 Freelancing & Digital Training",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "IGNITE / Ministry of IT & Telecom",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 12, "max_age": 70, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://digiskills.pk/",
        "document_checklist": json.dumps(["CNIC / B-Form", "Active Email Address"]),
        "apply_pathway": json.dumps(["Create account at digiskills.pk", "Enroll in 2 courses during open batch batch registration", "Watch online video lectures"])
    },
    {
        "program_id": "HEC_DLSEI",
        "name": "HEC Digital Learning & Skills Initiative (Coursera)",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "HEC & Coursera",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 17, "max_age": 35, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://dlsei.hec.gov.pk/",
        "document_checklist": json.dumps(["Student/Faculty University ID", "CNIC"]),
        "apply_pathway": json.dumps(["Register at dlsei.hec.gov.pk", "Get verification from university focal person", "Access Coursera catalog"])
    },
    {
        "program_id": "PSDF_SKILLS",
        "name": "PSDF Free Vocational & Technical Training",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "Punjab Skills Development Fund",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 15, "max_age": 35, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://www.psdf.org.pk/",
        "document_checklist": json.dumps(["Punjab Domicile", "CNIC / B-Form"]),
        "apply_pathway": json.dumps(["Search courses on psdf.org.pk", "Enroll in nearest PSDF affiliated institute"])
    },
    {
        "program_id": "KPITB_SKILLS",
        "name": "KPITB Digital Youth Empowerment Courses",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "Khyber Pakhtunkhwa IT Board",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 16, "max_age": 35, "allowed_regions": ["KPK"], "requires_license": False, "min_education_level": "Matric", "disability_quota_only": False}),
        "official_url": "https://www.kpitb.gov.pk/",
        "document_checklist": json.dumps(["KPK Domicile", "CNIC"]),
        "apply_pathway": json.dumps(["Visit kpitb.gov.pk", "Apply for active digital training bootcamps"])
    },
    {
        "program_id": "TEVTA_PUNJAB",
        "name": "TEVTA Short Technical & Vocational Courses",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "TEVTA Punjab",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 14, "max_age": 40, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://www.tevta.gop.pk/",
        "document_checklist": json.dumps(["Punjab Domicile", "Educational Marks Sheet"]),
        "apply_pathway": json.dumps(["Choose course on tevta.gop.pk", "Submit physical form at local TEVTA center"])
    },
    {
        "program_id": "STEVTA_SINDH",
        "name": "STEVTA Technical & Vocational Training Programs",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "Sindh TEVTA",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 14, "max_age": 40, "allowed_regions": ["Sindh"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "http://www.stevta.gos.pk/",
        "document_checklist": json.dumps(["Sindh Domicile", "CNIC / B-Form"]),
        "apply_pathway": json.dumps(["Apply online at stevta.gos.pk or regional institute"])
    },
    {
        "program_id": "GOOGLE_BUILD_FUTURE",
        "name": "Google Career Certificates & Student Developer Training",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "Google / Tech4Good",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 15, "max_age": 60, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://buildyourfuture.withgoogle.com/",
        "document_checklist": json.dumps(["Active Google Account"]),
        "apply_pathway": json.dumps(["Explore programs at buildyourfuture.withgoogle.com", "Join self-paced online learning pathways"])
    },
    {
        "program_id": "CISCO_NETACAD",
        "name": "Cisco Networking Academy Free IT & Cybersecurity Courses",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "Cisco Systems",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 13, "max_age": 70, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Primary", "disability_quota_only": False}),
        "official_url": "https://www.netacad.com/catalogs/learn",
        "document_checklist": json.dumps(["Valid Email Address"]),
        "apply_pathway": json.dumps(["Enroll directly at netacad.com", "Complete free courses on Linux, Cybersecurity, and Networking"])
    },
    {
        "program_id": "HEC_GENAI_PAKANGELS",
        "name": "HEC Generative AI National Training Program",
        "category": "🎓 Free Courses & Skill Development",
        "provider": "HEC & PakAngels",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 18, "max_age": 45, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://www.pakangels.com/hec-generative-ai-training-program/",
        "document_checklist": json.dumps(["CNIC", "Basic Programming Knowledge"]),
        "apply_pathway": json.dumps(["Register via pakangels.com page", "Complete AI assessment & join live cohort"])
    },

    # ------------------ ASSET SCHEMES ------------------
    {
        "program_id": "CM_PUNJAB_EBIKE",
        "name": "CM Punjab E-Bike & Scooty Scheme",
        "category": "🛵 Govt Asset Schemes (Bikes & Laptops)",
        "provider": "PITB & Transport Department Punjab",
        "eligibility_json": json.dumps({"max_income": 150000, "min_age": 18, "max_age": 35, "allowed_regions": ["Punjab"], "requires_license": True, "min_education_level": "Matric", "disability_quota_only": False}),
        "official_url": "https://bikes.punjab.gov.pk/",
        "document_checklist": json.dumps(["CNIC", "Punjab Domicile", "Driving/Learner License", "Special Person CNIC (for PWD reserved quota)"]),
        "apply_pathway": json.dumps(["Register on bikes.punjab.gov.pk", "Select E-bike or Scooty model", "Upload license and bank verification documents"])
    },
    {
        "program_id": "CM_PUNJAB_LAPTOP",
        "name": "CM Punjab Free Laptop Scheme",
        "category": "🛵 Govt Asset Schemes (Bikes & Laptops)",
        "provider": "Higher Education Department (HED) Punjab",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 16, "max_age": 30, "allowed_regions": ["Punjab"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://cmlaptophed.punjab.gov.pk/",
        "document_checklist": json.dumps(["CNIC / B-Form", "Punjab Domicile", "Transcript (65%+ required; Blind/Disabled candidates exempt)", "NADRA Disability Certificate"]),
        "apply_pathway": json.dumps(["Verify CNIC at cmlaptophed.punjab.gov.pk", "Confirm university roll number & merit standing", "Receive laptop from campus distribution center"])
    },
    {
        "program_id": "PMYP_ASSET_LAPTOP",
        "name": "Prime Minister's Youth Laptop & Business Loan Schemes",
        "category": "🛵 Govt Asset Schemes (Bikes & Laptops)",
        "provider": "PM Youth Programme",
        "eligibility_json": json.dumps({"max_income": None, "min_age": 18, "max_age": 35, "allowed_regions": ["All"], "requires_license": False, "min_education_level": "Intermediate", "disability_quota_only": False}),
        "official_url": "https://pmyp.gov.pk/",
        "document_checklist": json.dumps(["CNIC", "University Student ID", "Disability Card (for reserved allocation)"]),
        "apply_pathway": json.dumps(["Apply online via pmyp.gov.pk", "Select laptop or asset loan portal", "Track application online"])
    }
]

conn = backend.get_db_connection()
cursor = conn.cursor()
for prog in SEED_PROGRAMS:
    cursor.execute("""
        INSERT OR REPLACE INTO programs (program_id, name, category, provider, eligibility_json, official_url, document_checklist, apply_pathway)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (prog["program_id"], prog["name"], prog["category"], prog["provider"], prog["eligibility_json"], prog["official_url"], prog["document_checklist"], prog["apply_pathway"]))

conn.commit()
conn.close()

print("✅ Comprehensive dataset seeded into aidmatch.db with all official links.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import json
# from backend import init_db, register_user, authenticate_user, run_matching_pipeline, get_user_search_history, GroqAssistant
# 
# st.set_page_config(page_title="AidMatch Pakistan", page_icon="🇵🇰", layout="wide")
# 
# st.markdown("""
# <style>
#     .main-header { font-size: 2.2rem; color: #006633; font-weight: bold; text-align: center; margin-bottom: 0px; }
#     .sub-header { font-size: 1.1rem; color: #555; text-align: center; margin-bottom: 20px; }
#     .card-eligible { background-color: #f4fbf7; border-radius: 10px; padding: 18px; border-left: 6px solid #28a745; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
#     .card-conditional { background-color: #fffdf5; border-radius: 10px; padding: 18px; border-left: 6px solid #ffc107; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
#     .card-ineligible { background-color: #fff8f8; border-radius: 10px; padding: 18px; border-left: 6px solid #dc3545; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
#     .badge-eligible { background-color: #28a745; color: white; padding: 5px 12px; border-radius: 12px; font-weight: bold; float: right; }
#     .badge-conditional { background-color: #ffc107; color: black; padding: 5px 12px; border-radius: 12px; font-weight: bold; float: right; }
#     .badge-ineligible { background-color: #dc3545; color: white; padding: 5px 12px; border-radius: 12px; font-weight: bold; float: right; }
# </style>
# """, unsafe_allow_html=True)
# 
# init_db()
# 
# if "authenticated" not in st.session_state:
#     st.session_state["authenticated"] = False
# if "user" not in st.session_state:
#     st.session_state["user"] = None
# if "messages" not in st.session_state:
#     st.session_state["messages"] = []
# 
# # AUTHENTICATION WALL
# if not st.session_state["authenticated"]:
#     st.markdown("<div class='main-header'>🇵🇰 AidMatch Pakistan</div>", unsafe_allow_html=True)
#     st.markdown("<div class='sub-header'>Free Government Schemes, Scholarships & Skill Discovery Portal</div>", unsafe_allow_html=True)
# 
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col2:
#         tab1, tab2 = st.tabs(["🔒 Sign In", "📝 Create Account"])
# 
#         with tab1:
#             st.subheader("Sign In to Your Private Account")
#             login_email = st.text_input("Gmail / Email Address", key="login_email")
#             login_pass = st.text_input("Password", type="password", key="login_pass")
# 
#             if st.button("Sign In", use_container_width=True):
#                 if login_email and login_pass:
#                     res = authenticate_user(login_email, login_pass)
#                     if res["success"]:
#                         st.session_state["authenticated"] = True
#                         st.session_state["user"] = res["user"]
#                         st.success("Authenticated successfully!")
#                         st.rerun()
#                     else:
#                         st.error(res["error"])
#                 else:
#                     st.warning("Please enter both email and password.")
# 
#         with tab2:
#             st.subheader("Create New Private Account")
#             reg_name = st.text_input("Full Name", key="reg_name")
#             reg_email = st.text_input("Gmail / Email Address", key="reg_email")
#             reg_cnic = st.text_input("13-Digit CNIC", key="reg_cnic")
#             reg_pass = st.text_input("Set Private Password", type="password", key="reg_pass")
# 
#             if st.button("Create Account & Sign In", use_container_width=True):
#                 if reg_name and reg_email and reg_cnic and reg_pass:
#                     res = register_user(reg_email, reg_pass, reg_cnic, reg_name)
#                     if res["success"]:
#                         st.session_state["authenticated"] = True
#                         st.session_state["user"] = res["user"]
#                         st.success("Account created successfully!")
#                         st.rerun()
#                     else:
#                         st.error(res["error"])
#                 else:
#                     st.warning("All fields are required.")
#     st.stop()
# 
# # PRIVATE LOGGED-IN SIDEBAR
# st.sidebar.title(f"👤 {st.session_state['user']['name']}")
# st.sidebar.caption(f"Logged in as: {st.session_state['user']['email']}")
# 
# nav_choice = st.sidebar.radio("Navigation Category", [
#     "🎓 Free Courses & Skill Development",
#     "💰 Scholarships & Financial Assistance",
#     "🛵 Govt Asset Schemes (Bikes & Laptops)",
#     "📜 Private Search History",
#     "💬 Bilingual Assistant / مددگار"
# ])
# 
# if st.sidebar.button("Logout / Lock Session"):
#     st.session_state["authenticated"] = False
#     st.session_state["user"] = None
#     st.session_state["messages"] = []
#     st.rerun()
# 
# # RESULTS RENDERER
# def render_all_results(results):
#     st.subheader(f"📊 Evaluated Opportunities Matrix ({len(results)} Total Programs)")
#     st.caption("All programs in this category are evaluated for your account profile.")
# 
#     if not results:
#         st.info("No records found.")
#         return
# 
#     sorted_results = sorted(results, key=lambda x: 0 if x["status"] == "Eligible" else 1 if x["status"] == "Conditional" else 2)
# 
#     for res in sorted_results:
#         prog = res["program"]
#         status = res["status"]
#         card_class = f"card-{status.lower()}"
#         badge_class = f"badge-{status.lower()}"
# 
#         st.markdown(f"""
#         <div class='{card_class}'>
#             <span class='{badge_class}'>{status}</span>
#             <h3 style='margin-top:0;'>{prog['name']}</h3>
#             <p><b>Managing Provider:</b> {prog['provider']}</p>
#         </div>
#         """, unsafe_allow_html=True)
# 
#         if status == "Ineligible":
#             st.error("**❌ Why You Are Not Eligible:**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
#         elif status == "Conditional":
#             st.warning("**⚠️ Conditional Eligibility Notes:**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
#             if res["missing_info"]:
#                 st.write("**Action Needed:** " + ", ".join(res["missing_info"]))
#         else:
#             st.success("**✅ You Meet All Eligibility Criteria!**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
# 
#         col_a, col_b = st.columns(2)
#         with col_a:
#             st.write("**📋 Required Documents & Quotas:**")
#             for doc in prog["document_checklist"]:
#                 st.checkbox(doc, key=f"{prog['program_id']}_{doc}")
#         with col_b:
#             st.write("**🚀 Direct Application Pathway:**")
#             for idx, step in enumerate(prog["apply_pathway"], 1):
#                 st.write(f"{idx}. {step}")
# 
#         st.link_button(f"Visit Official Portal ({prog['provider']})", prog["official_url"])
#         st.divider()
# 
# # CATEGORY EVALUATION FORMS
# if nav_choice in ["🎓 Free Courses & Skill Development", "💰 Scholarships & Financial Assistance", "🛵 Govt Asset Schemes (Bikes & Laptops)"]:
#     st.title(nav_choice)
# 
#     with st.form("search_form"):
#         st.subheader("📋 Profile Evaluation Form")
#         col1, col2 = st.columns(2)
#         with col1:
#             income = st.number_input("Monthly Household Income (PKR)", min_value=0, value=45000, step=5000)
#             age = st.number_input("Applicant Age", min_value=10, max_value=80, value=22)
#             domicile = st.selectbox("Domicile / Residence District", ["Punjab", "Federal / ICT", "Sindh", "KPK", "Balochistan", "AJK / GB"])
#         with col2:
#             education = st.selectbox("Current / Highest Qualification", ["Primary", "Matric", "Intermediate", "Bachelors", "Masters", "PhD"])
#             is_disabled = st.checkbox("♿ Person with Disability / Special Person (Holding NADRA Special CNIC / Certificate)")
#             license_status = st.checkbox("🛵 Holds Valid Driving / Learner License") if "Asset Schemes" in nav_choice else False
# 
#         submit_btn = st.form_submit_button("Evaluate All Programs in This Category")
# 
#     if submit_btn:
#         profile = {
#             "user_id": st.session_state["user"]["user_id"],
#             "cnic": st.session_state["user"]["cnic"],
#             "category": nav_choice,
#             "monthly_income": income,
#             "age": age,
#             "domicile": domicile,
#             "education_level": education,
#             "is_disabled": is_disabled,
#             "has_driving_license": license_status
#         }
#         results = run_matching_pipeline(profile)
#         render_all_results(results)
# 
# # PRIVATE SEARCH HISTORY LOG
# elif nav_choice == "📜 Private Search History":
#     st.title("📜 Private Search History Log")
#     st.caption("This log contains only search queries performed under your account.")
# 
#     history = get_user_search_history(st.session_state["user"]["user_id"])
# 
#     if not history:
#         st.info("No saved search history found for your account.")
#     else:
#         for item in history:
#             with st.expander(f"Search Record #{item['search_id']} - {item['category']} ({item['timestamp']})"):
#                 st.json(item["profile"])
#                 st.write(f"Matched Program IDs: `{item['matches']}`")
# 
# # BILINGUAL CHATBOT
# elif nav_choice == "💬 Bilingual Assistant / مددگار":
#     st.title("💬 Bilingual Assistant / مددگار AI")
#     st.caption("Ask questions about disability quotas, document requirements, or portal applications in English or Urdu.")
# 
#     bot = GroqAssistant()
# 
#     for msg in st.session_state["messages"]:
#         st.chat_message(msg["role"]).write(msg["content"])
# 
#     user_input = st.chat_input("سوال پوچھیں یا کہئے Ask a question...")
#     if user_input:
#         st.session_state["messages"].append({"role": "user", "content": user_input})
#         st.chat_message("user").write(user_input)
# 
#         with st.chat_message("assistant"):
#             with st.spinner("Searching official guidance..."):
#                 response = bot.generate_bilingual_response(user_input, st.session_state["messages"][:-1])
#                 st.write(response)
#                 st.session_state["messages"].append({"role": "assistant", "content": response})

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import json
# from backend import init_db, register_user, authenticate_user, run_matching_pipeline, get_user_search_history, GroqAssistant
# 
# st.set_page_config(page_title="AidMatch Pakistan", page_icon="🇵🇰", layout="wide")
# 
# # High-Contrast Dark Theme CSS
# st.markdown("""
# <style>
#     .main-header { font-size: 2.4rem; color: #10b981; font-weight: 800; text-align: center; margin-bottom: 5px; }
#     .sub-header { font-size: 1.1rem; color: #9ca3af; text-align: center; margin-bottom: 25px; }
# 
#     /* Modern Header Banner Cards */
#     .program-card {
#         background: linear-gradient(135deg, #111827 0%, #1f2937 100%);
#         border-radius: 12px;
#         padding: 22px 25px;
#         margin-bottom: 18px;
#         box-shadow: 0 4px 15px rgba(0, 0, 0, 0.4);
#         border: 1px solid #374151;
#     }
#     .card-eligible { border-left: 8px solid #10b981; }
#     .card-conditional { border-left: 8px solid #f59e0b; }
#     .card-ineligible { border-left: 8px solid #ef4444; }
# 
#     .program-title {
#         font-size: 1.65rem !important;
#         font-weight: 800 !important;
#         color: #ffffff !important;
#         margin: 0 0 8px 0 !important;
#         line-height: 1.3 !important;
#         letter-spacing: -0.01em !important;
#     }
#     .program-provider {
#         font-size: 1.05rem !important;
#         color: #38bdf8 !important;
#         font-weight: 600 !important;
#         margin: 0 !important;
#     }
#     .badge-eligible {
#         background-color: #10b981;
#         color: #ffffff;
#         padding: 6px 14px;
#         border-radius: 20px;
#         font-size: 0.85rem;
#         font-weight: 700;
#         text-transform: uppercase;
#         letter-spacing: 0.05em;
#     }
#     .badge-conditional {
#         background-color: #f59e0b;
#         color: #000000;
#         padding: 6px 14px;
#         border-radius: 20px;
#         font-size: 0.85rem;
#         font-weight: 700;
#         text-transform: uppercase;
#         letter-spacing: 0.05em;
#     }
#     .badge-ineligible {
#         background-color: #ef4444;
#         color: #ffffff;
#         padding: 6px 14px;
#         border-radius: 20px;
#         font-size: 0.85rem;
#         font-weight: 700;
#         text-transform: uppercase;
#         letter-spacing: 0.05em;
#     }
# </style>
# """, unsafe_allow_html=True)
# 
# init_db()
# 
# if "authenticated" not in st.session_state:
#     st.session_state["authenticated"] = False
# if "user" not in st.session_state:
#     st.session_state["user"] = None
# if "messages" not in st.session_state:
#     st.session_state["messages"] = []
# 
# # AUTHENTICATION WALL
# if not st.session_state["authenticated"]:
#     st.markdown("<div class='main-header'>🇵🇰 AidMatch Pakistan</div>", unsafe_allow_html=True)
#     st.markdown("<div class='sub-header'>Free Government Schemes, Scholarships & Skill Discovery Portal</div>", unsafe_allow_html=True)
# 
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col2:
#         tab1, tab2 = st.tabs(["🔒 Sign In", "📝 Create Account"])
# 
#         with tab1:
#             st.subheader("Sign In to Your Private Account")
#             login_email = st.text_input("Gmail / Email Address", key="login_email")
#             login_pass = st.text_input("Password", type="password", key="login_pass")
# 
#             if st.button("Sign In", use_container_width=True):
#                 if login_email and login_pass:
#                     res = authenticate_user(login_email, login_pass)
#                     if res["success"]:
#                         st.session_state["authenticated"] = True
#                         st.session_state["user"] = res["user"]
#                         st.success("Authenticated successfully!")
#                         st.rerun()
#                     else:
#                         st.error(res["error"])
#                 else:
#                     st.warning("Please enter both email and password.")
# 
#         with tab2:
#             st.subheader("Create New Private Account")
#             reg_name = st.text_input("Full Name", key="reg_name")
#             reg_email = st.text_input("Gmail / Email Address", key="reg_email")
#             reg_cnic = st.text_input("13-Digit CNIC", key="reg_cnic")
#             reg_pass = st.text_input("Set Private Password", type="password", key="reg_pass")
# 
#             if st.button("Create Account & Sign In", use_container_width=True):
#                 if reg_name and reg_email and reg_cnic and reg_pass:
#                     res = register_user(reg_email, reg_pass, reg_cnic, reg_name)
#                     if res["success"]:
#                         st.session_state["authenticated"] = True
#                         st.session_state["user"] = res["user"]
#                         st.success("Account created successfully!")
#                         st.rerun()
#                     else:
#                         st.error(res["error"])
#                 else:
#                     st.warning("All fields are required.")
#     st.stop()
# 
# # PRIVATE LOGGED-IN SIDEBAR
# st.sidebar.title(f"👤 {st.session_state['user']['name']}")
# st.sidebar.caption(f"Logged in as: {st.session_state['user']['email']}")
# 
# nav_choice = st.sidebar.radio("Navigation Category", [
#     "🎓 Free Courses & Skill Development",
#     "💰 Scholarships & Financial Assistance",
#     "🛵 Govt Asset Schemes (Bikes & Laptops)",
#     "📜 Private Search History",
#     "💬 Bilingual Assistant / مددگار"
# ])
# 
# if st.sidebar.button("Logout / Lock Session"):
#     st.session_state["authenticated"] = False
#     st.session_state["user"] = None
#     st.session_state["messages"] = []
#     st.rerun()
# 
# # RESULTS RENDERER
# def render_all_results(results):
#     st.subheader(f"📊 Evaluated Opportunities Matrix ({len(results)} Total Programs)")
#     st.caption("All programs in this category are evaluated for your account profile.")
# 
#     if not results:
#         st.info("No records found.")
#         return
# 
#     sorted_results = sorted(results, key=lambda x: 0 if x["status"] == "Eligible" else 1 if x["status"] == "Conditional" else 2)
# 
#     for res in sorted_results:
#         prog = res["program"]
#         status = res["status"]
#         card_class = f"card-{status.lower()}"
#         badge_class = f"badge-{status.lower()}"
# 
#         # High-impact banner card replacing white block
#         st.markdown(f"""
#         <div class='program-card {card_class}'>
#             <div style='display: flex; justify-content: space-between; align-items: flex-start; gap: 15px;'>
#                 <div style='flex-grow: 1;'>
#                     <div class='program-title'>🏛️ {prog['name']}</div>
#                     <div class='program-provider'><b>Managing Provider:</b> {prog['provider']}</div>
#                 </div>
#                 <div>
#                     <span class='{badge_class}'>{status}</span>
#                 </div>
#             </div>
#         </div>
#         """, unsafe_allow_html=True)
# 
#         if status == "Ineligible":
#             st.error("**❌ Why You Are Not Eligible:**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
#         elif status == "Conditional":
#             st.warning("**⚠️ Conditional Eligibility Notes:**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
#             if res["missing_info"]:
#                 st.write("**Action Needed:** " + ", ".join(res["missing_info"]))
#         else:
#             st.success("**✅ You Meet All Eligibility Criteria!**")
#             for r in res["reasons"]:
#                 st.write(f"• {r}")
# 
#         col_a, col_b = st.columns(2)
#         with col_a:
#             st.write("**📋 Required Documents & Quotas:**")
#             for doc in prog["document_checklist"]:
#                 st.checkbox(doc, key=f"{prog['program_id']}_{doc}")
#         with col_b:
#             st.write("**🚀 Direct Application Pathway:**")
#             for idx, step in enumerate(prog["apply_pathway"], 1):
#                 st.write(f"{idx}. {step}")
# 
#         st.link_button(f"Visit Official Portal ({prog['provider']})", prog["official_url"])
#         st.divider()
# 
# # CATEGORY EVALUATION FORMS
# if nav_choice in ["🎓 Free Courses & Skill Development", "💰 Scholarships & Financial Assistance", "🛵 Govt Asset Schemes (Bikes & Laptops)"]:
#     st.title(nav_choice)
# 
#     with st.form("search_form"):
#         st.subheader("📋 Profile Evaluation Form")
#         col1, col2 = st.columns(2)
#         with col1:
#             income = st.number_input("Monthly Household Income (PKR)", min_value=0, value=45000, step=5000)
#             age = st.number_input("Applicant Age", min_value=10, max_value=80, value=22)
#             domicile = st.selectbox("Domicile / Residence District", ["Punjab", "Federal / ICT", "Sindh", "KPK", "Balochistan", "AJK / GB"])
#         with col2:
#             education = st.selectbox("Current / Highest Qualification", ["Primary", "Matric", "Intermediate", "Bachelors", "Masters", "PhD"])
#             is_disabled = st.checkbox("♿ Person with Disability / Special Person (Holding NADRA Special CNIC / Certificate)")
#             license_status = st.checkbox("🛵 Holds Valid Driving / Learner License") if "Asset Schemes" in nav_choice else False
# 
#         submit_btn = st.form_submit_button("Evaluate All Programs in This Category")
# 
#     if submit_btn:
#         profile = {
#             "user_id": st.session_state["user"]["user_id"],
#             "cnic": st.session_state["user"]["cnic"],
#             "category": nav_choice,
#             "monthly_income": income,
#             "age": age,
#             "domicile": domicile,
#             "education_level": education,
#             "is_disabled": is_disabled,
#             "has_driving_license": license_status
#         }
#         results = run_matching_pipeline(profile)
#         render_all_results(results)
# 
# # PRIVATE SEARCH HISTORY LOG
# elif nav_choice == "📜 Private Search History":
#     st.title("📜 Private Search History Log")
#     st.caption("This log contains only search queries performed under your account.")
# 
#     history = get_user_search_history(st.session_state["user"]["user_id"])
# 
#     if not history:
#         st.info("No saved search history found for your account.")
#     else:
#         for item in history:
#             with st.expander(f"Search Record #{item['search_id']} - {item['category']} ({item['timestamp']})"):
#                 st.json(item["profile"])
#                 st.write(f"Matched Program IDs: `{item['matches']}`")
# 
# # BILINGUAL CHATBOT
# elif nav_choice == "💬 Bilingual Assistant / مددگار":
#     st.title("💬 Bilingual Assistant / مددگار AI")
#     st.caption("Ask questions about disability quotas, document requirements, or portal applications in English or Urdu.")
# 
#     bot = GroqAssistant()
# 
#     for msg in st.session_state["messages"]:
#         st.chat_message(msg["role"]).write(msg["content"])
# 
#     user_input = st.chat_input("سوال پوچھیں یا کہئے Ask a question...")
#     if user_input:
#         st.session_state["messages"].append({"role": "user", "content": user_input})
#         st.chat_message("user").write(user_input)
# 
#         with st.chat_message("assistant"):
#             with st.spinner("Searching official guidance..."):
#                 response = bot.generate_bilingual_response(user_input, st.session_state["messages"][:-1])
#                 st.write(response)
#                 st.session_state["messages"].append({"role": "assistant", "content": response})

import os
import subprocess
import time

# 1. Kill stale background processes
subprocess.run(["pkill", "-f", "streamlit"], stderr=subprocess.DEVNULL)
subprocess.run(["pkill", "-f", "cloudflared"], stderr=subprocess.DEVNULL)

# 2. Download cloudflared binary if missing
if not os.path.exists("cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
    !chmod +x cloudflared
    print("✅ Downloaded Cloudflare Tunnel binary.")

# 3. Start Streamlit in background
process = subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"])
print("🚀 Streamlit app starting on port 8501...")
time.sleep(5)

# 4. Launch Cloudflare Tunnel and retrieve public URL
print("\n🌐 Establishing Secure Cloudflare Tunnel...")
tunnel_process = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True
)

url_found = False
for _ in range(25):
    line = tunnel_process.stderr.readline()
    if "trycloudflare.com" in line:
        for token in line.split():
            if "https://" in token and "trycloudflare.com" in token:
                print(f"\n🎉 AidMatch Portal Live URL: {token}\n")
                url_found = True
                break
    if url_found:
        break
    time.sleep(1)

if not url_found:
    print("⚡ Tunnel started! Re-run cell if URL did not print in stdout.")